Php
airdeploy/airdeploy-docs pull request #20
Opened 2021-02-02 17:06 UTC by jeronimo13

Note: branch out from https://github.com/airdeploy/airdeploy-docs/pull/19

2021-02-02 23:12 UTC, thealveen requested changes
minor comments here, code snippets parts look good

2021-02-02 23:12 UTC, thealveen commented on docs/api-reference/go.md
> +Explicitly notifies Airdeploy about an Entity
this grammar correction is incorrect. revert this

2021-02-02 23:12 UTC, thealveen commented on docs/api-reference/js.md
> +Explicitly notifies Airdeploy about an Entity
All of them

2021-02-02 23:12 UTC, thealveen commented on docs/api-reference/php.md
> +- If second(third …) call of `init` happens:
space between second and parantheses

2021-02-04 13:08 UTC, jeronimo13 commented on docs/api-reference/go.md
> +Explicitly notifies Airdeploy about an Entity
https://make.wordpress.org/core/handbook/best-practices/inline-documentation-standards/php/#language

"It" or "This function" is implied. If it's incorrect for `Publish` function, are other cases correct where "It' is omitted, like this one:
```
    /**
     * Determines if flag is enabled for entity.
     *
     * @param string $codename
     * @param null $entity
     * @return bool
     */
    public static function isEnabled(string $codename, $entity = null): bool
```

2021-03-16 12:44 UTC, merged